app: lambda-report
service: lambda-report

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  report:
    handler: report.lambdaFunction
    events:
      - http:
          path: /report
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

